<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Storecredit
 * @version    1.0.5
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><script type="text/javascript">
    Event.observe(document, 'dom:loaded', function(){
        window.order.loadArea(['totals','billing_method'], true);
    });
</script>
<?php if ($this->isAllowed()): ?>
    <input type="checkbox" id="use_storecredit" class="checkbox" <?php echo ($this->isStorecreditUsed() ? 'checked' : '') ?>/>
    <?php $balance = $this->getFormattedBalance(); ?>
    <label for="use_storecredit">
        <strong>
            <?php echo Mage::helper('aw_storecredit')->__('Use Store Credit'); ?>
            (<?php echo $balance; ?> <?php echo Mage::helper('aw_storecredit')->__('available'); ?>)
        </strong>
    </label>
    <script type="text/javascript">
        $$('#use_storecredit').first().observe('change', function(event) {
            var value = $(this).checked ? 1 : 0;
            new Ajax.Request(<?php echo Zend_Json::encode($this->getUrlStoreCreditSave()); ?>, {
                method: 'get',
                parameters: {
                    use_storecredit: value
                },
                onSuccess: function() {
                    window.order.loadArea(['totals','billing_method'], true);
                }
            });
        });
    </script>
<?php endif; ?>
